# Generated by Django 2.2.3 on 2019-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190727_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='score_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
